// Code generated by "stringer -type HandType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[HighCard-1]
	_ = x[OnePair-2]
	_ = x[TwoPair-3]
	_ = x[ThreeOfAKind-4]
	_ = x[FullHouse-5]
	_ = x[FourOfAKind-6]
	_ = x[FiveOfAKind-7]
}

const _HandType_name = "UnknownHighCardOnePairTwoPairThreeOfAKindFullHouseFourOfAKindFiveOfAKind"

var _HandType_index = [...]uint8{0, 7, 15, 22, 29, 41, 50, 61, 72}

func (i HandType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_HandType_index)-1 {
		return "HandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HandType_name[_HandType_index[idx]:_HandType_index[idx+1]]
}
